# Generated by Django 4.2.5 on 2023-09-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_section_parent_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='books.book'),
        ),
    ]
